### ISSUE TITLE
Copilot doesn´t work 'TypeError: window.mountChainlitWidget'

### ISSUE THREAD

**Issue by RicardoRobledo** [Chainlit/cookbook#102]
I am trying to build a chainlit app with copilot, but I can't get the copilot.

<br>

I only installed chainlit and run the file following the tutorial.

>Uncaught TypeError: Failed to construct 'URL': Invalid URL
    at index.js:275:3885
    at index.js:4208:91586
index.html:12
Uncaught TypeError: window.mountChainlitWidget is not a function
    at index.html:12:12

<br>

Code:
```python
import chainlit as cl


@cl.on_message
async def on_message(msg: cl.Message):
    if cl.context.session.client_type == "copilot":
        fn = cl.CopilotFunction(name="test", args={"msg": msg.content})
        res = await fn.acall()
        await cl.Message(content=res).send()
```

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    </script>
<script src="http://localhost:8000/copilot/index.js"></script>
  <script>
    window.mountChainlitWidget({
      chainlitServer: "http://localhost:8000",
    });
  </script>
</body>
</html>
```

![image](https://github.com/Chainlit/cookbook/assets/99063411/b575edc6-d3d4-4a38-9b15-f485fa46a319)

**Comment by ModEnter** [comment]
Hello, the copilot example has been fixed, and the old config files that were responsible for this issue have been removed. I'm closing the issue
