### ISSUE TITLE
Changer le logo

### ISSUE THREAD

**Issue by PapaLoupSkies** [Chainlit/cookbook#107]
![Capture d'écran 2024-05-05 012220](https://github.com/Chainlit/cookbook/assets/73849425/47694ea5-c3ca-43e3-9d47-46e7bc543d1e)

Bonjour,  pouvez-vous m'indiquer comment changer le logo ? J'ai essayé de les mettre dans un répertoire "Public", ca ne marche pas ...

Merci

**Comment by ModEnter** [comment]
Bonjour, vous devez suivre les étapes indiquées [ici](https://github.com/Chainlit/cookbook/issues/119). J'ai ajouté un warning dans le dossier. Je ferme l'issue
