### ISSUE TITLE
Please update to latest Langchain usage.

### ISSUE THREAD

**Issue by atljoseph** [Chainlit/cookbook#109]
This repo is months behind the main one, and months behind Langchain. 

Langchain’s acall is deprecated and should use ainvoke, which works differently. 

@cl.step decorator is broken. Using acall, it worked. Using ainvoke, nothing. It’s a black box :/

I can’t think of a worse way to introduce a product to someone than to tell them how awesome a new thing is, and then throw old and misleading info at them. 

Also, langgraph examples would be nice.

**Comment by constantinidan** [comment]
Totally right. Updating them.
