### ISSUE TITLE
Chat Resume - Dates of previous and current conversations

### ISSUE THREAD

**Issue by smannathan** [Chainlit/cookbook#111]
The resume feature for chats operates smoothly, allowing conversations to continue without interruption. However, it lacks a crucial function: it does not display the dates of previous interactions. This omission makes it challenging to track the timeline of conversations, which could be essential for referencing past discussions or understanding the context of ongoing dialogues.

**Comment by constantinidan** [comment]
Great point thank you! Adding that to bugfixes list.
