### ISSUE TITLE
How do we change logo

### ISSUE THREAD

**Issue by duncanodhis** [Chainlit/cookbook#112]
I tried the cookbook  logo example ,it didn't work

**Comment by dxv2k** [comment]
+1 it didn't work too

**Comment by Prem-Nitin** [comment]
Clear the browser cache and try launching the app, it should work

**Comment by Radeeshp** [comment]
did that work?

**Comment by DaneshJoy** [comment]
Logo change is not applied in chrome. Even after clearing the cache!
But it works in Firefox for me (after clearing the cache).

The only thing that made it work in chrome for me was changing the port and running on the new port:
`chainlit run --port 8002 cl_app.py -w`

**Comment by ModEnter** [comment]
For more details, please refer to [this](https://github.com/Chainlit/cookbook/issues/119) issue. I'm marking this one as resolved.
