### ISSUE TITLE
Extend CoPilot example

### ISSUE THREAD

**Issue by tituslhy** [Chainlit/cookbook#113]
Hello!

I'm building a ReAct agent on top of Chainlit CoPilot which will be mounted on a HTML file. I'm able to code the invoking of the agent and streaming of response in Chainlit using Python, but the Chainlit CoPilot requires a callback function within JavaScript event listener.

I'm thinking of deploying my LLM agent as a FastAPI returning a StreamingResponse that will be called by the callback function in the index.html file. How do I adapt the callback function accordingly to stream the response in the CoPilot? Do you have a simple example of streaming a simple reply via an API call?

Much appreciated!

Sample codes:

**api.py**
```
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
import time

app = FastAPI()

app.add_middleware(CORSMiddleware,
                   allow_origins=["*"],
                   allow_credentials = True,
                   allow_methods=["*"],
                   allow_headers=["*"])

async def fake_video_streamer():
    string = "some fake video bytes"
    for word in string.split():
        time.sleep(1)
        yield word
        
@app.get("/")
async def main():
    return StreamingResponse(fake_video_streamer(),
                             media_type='text/event-stream')
```

And here's the HTML file:
```
<body>
    <script src="http://localhost:8000/copilot/index.js"></script>
    <script>
        
        window.mountChainlitWidget({
        chainlitServer: "http://localhost:8000",
        });
        window.addEventListener("chainlit-call-fn", (e) => {
            const { name, args, callback } = e.detail;
            if (name === "test") {

              callback("You sent: " + args.msg); //send the results in this callback function <- How do I edit this callback function to stream completion?
            }
          });
    </script>
</body>
```

**Comment by willydouhard** [comment]
I am not sure why you want to have another fast API server and use http requests. I would just use the Chainlit abstraction for [function calling](https://docs.chainlit.io/deployment/copilot#function-calling). If you need to expose something as an API, you can use [custom API endpoints](https://docs.chainlit.io/backend/custom-endpoint).

**Comment by tituslhy** [comment]
Sorry I think I'm just not very good at JavaScript. Maybe just to be more specific, how do I edit this line of code to send the query to the chainlit server? Or does the callback() function already handle that?

```
window.addEventListener("chainlit-call-fn", (e) => {
  const { name, args, callback } = e.detail;
  if (name === "test") {
    console.log(name, args);
    callback("You sent: " + args.msg);
  }
});
```

And, can I check if I edited the on_message function correctly to incorporate the CoPilot's response?
```
@cl.on_message
async def on_message(message: cl.Message):
    agent = cl.user_session.get("agent")
    response_message = await cl.Message(content="").send()
    cl.user_session.set("response_message", response_message)
    response = await cl.make_async(agent.stream_chat)(message.content)
    if cl.context.session.client_type == "copilot":
        fn = cl.CopilotFunction(name="test", args={"msg": response.content}) #check syntax for response
        res = await fn.acall()
        await cl.Message(content=res).send()
```

**Comment by tituslhy** [comment]
> I am not sure why you want to have another fast API server and use http requests. I would just use the Chainlit abstraction for [function calling](https://docs.chainlit.io/deployment/copilot#function-calling). If you need to expose something as an API, you can use [custom API endpoints](https://docs.chainlit.io/backend/custom-endpoint).

Sorry I'm not sure if I understand how to do this. I was reading through the source code on GitHub and I'm unsure of how to do this. The CoPilot function in backend > chainlit > __init__.py sends a call using context.emitter.send_call(self.name, self.args). Are you suggesting for me to inherit the chainlit CoPilot class and add methods to it to send queries to an LLM?

If you have an example of how to use the CoPilot function abstraction that'll be greatly appreciated!

**Comment by tituslhy** [comment]
@willydouhard I think I figured it out! Minimum code sample
```
@cl.on_message
async def on_message(msg: cl.Message):
    llm = cl.user_session.get("llm")
    if cl.context.session.client_type == "copilot":
        response = llm.complete(msg.content)
        fn = cl.CopilotFunction(name="test", args={"response": str(response)})
        res = await fn.acall()
        await cl.Message(content=res).send()
```
How do I make the CoPilot stream the response?

**Comment by tituslhy** [comment]
Sorry just to update that I've figured it out! Minimum working sample!

@willydouhard sorry for the confusion and thanks for helping!

```
@cl.on_message
async def on_message(msg: cl.Message):
    llm = cl.user_session.get("llm")
    
    if cl.context.session.client_type == "copilot":
        response_message = await cl.Message("").send()
        response = await cl.make_async(llm.stream_complete)(msg.content)
        for chunk in response:
            await response_message.stream_token(chunk.delta)
        await response_message.update()
        fn = cl.CopilotFunction(name="test", args = {"msg": msg.content, "response": str(response_message)})
        res = await fn.acall()
```
