### ISSUE TITLE
Add a custom logo 

### ISSUE THREAD

**Issue by Parth4747** [Chainlit/cookbook#119]
When I try to add a custom logo to my already-made AI Assistant , I made a folder named public and put the logo in it. I then restarted my application based on the given example of the "custom-logo" but when I restarted my application, my logo was not visible, and the default logo of ChainLit was visible. If there is any further procedure ID there, please give me steps for that.

**Comment by chibexme** [comment]
I have this is too on the latest version at the moment version 1.1.300rc5

**Comment by AIprjcts** [comment]
I had the same problem too. Try to rename your logo file name to logo_dark.png and logo_light.png, for me that worked with the last version 1.1.300.

**Comment by BachNgoH** [comment]
Maybe you should delete your cache and restart your application

**Comment by Amogh1506** [comment]
cleared cache. kept logo_light.png and logo_dark.png in public folder. Still doesnt work..any suggestion?

**Comment by SebasUrbina** [comment]
I have the same problem, I created the "public" folder with logo_dark.png and logo_light.png inside but it doesnt change. Im using the 1.1.402 version.

**Comment by VioletRaven** [comment]
Yes, it doesn't work...

**Comment by SebasUrbina** [comment]
Finally I cleaned the cache and re-run the app and it worked :). Just make sure you clean the cache its the main problem.

**Comment by VioletRaven** [comment]
It does work on google chrome though... Do you guys have any idea on how to make my logo bigger? The css custom stylesheet does not work at all...

**Comment by voycey** [comment]
I have tried everything to clear cache etc but the logo wont take at all!

**Comment by DaneshJoy** [comment]
Logo change is not applied in chrome. Even after clearing the cache!
But it works in Firefox for me (after clearing the cache).

The only thing that made it work in chrome for me was changing the port and running on the new port:
`chainlit run --port 8002 cl_app.py -w`

**Comment by DaneshJoy** [comment]
> It does work on google chrome though... Do you guys have any idea on how to make my logo bigger? The css custom stylesheet does not work at all...

This css code worked for me in version 1.1.402 (to make the logo bigger):
```css
#header > img:nth-child(2) {
    max-height: 40px !important;
}

.css-14k6mw7 > img:nth-child(1) {
    max-height: 40px !important;
}
```

**Comment by VioletRaven** [comment]
> This css code worked for me in version 1.1.402 (to make the logo bigger):



It does not work for me at all. The css code in stylesheet.css file is not being read by chainlit...

**Comment by voycey** [comment]
The caching is pretty vicious on it, even after clearing cache you need to right click the image and open in a new tab and the refresh that image directly on that page after clearing the cache

**Comment by ModEnter** [comment]
The issue seems to be related to the way chrome caches images. I added a warning in the `custom-logo` to warn about this problem. I'm closing this issue

**Comment by gsubiran-megalabs** [comment]
Workaround:

First make sure you have the correct files at public folder named logo_light.png and logo_dark.png

From browser access to http://localhost:8000/logo?theme=light and then hit CTRL + F5
Also do the same for http://localhost:8000/logo?theme=dark

After that jus refresh the site and you will se the updated logo. Is not needed to re run the application

**Comment by gsubiran** [comment]
Workaround:

First make sure you have the correct files at _public_ folder 📂 named _logo_light.png_ and _logo_dark.png_

From browser access to [](http://localhost:8000/logo?theme=light) and then hit CTRL + F5
Also do the same for [](http://localhost:8000/logo?theme=dark)

After that jus refresh the site and you will se the updated logo. Is not needed to re run the application.

**Comment by nhatkhangcs** [comment]
@gsubiran Sorry, but what's the behaviour when you hit Ctrl+F5? Like is it supposed to pop up anything? Mine didn't work tho...
Thank you for any responses!

**Comment by gsubiran** [comment]
> [@gsubiran](https://github.com/gsubiran) Sorry, but what's the behaviour when you hit Ctrl+F5? Like is it supposed to pop up anything? Mine didn't work tho... Thank you for any responses!

Is just to refresh cached version of the image

https://www.debugbar.com/what-does-ctrl-f5-do/
