### ISSUE TITLE
Document prompt requires documents to have metadata variables: ['source']. Received document with missing metadata: ['source'].

### ISSUE THREAD

**Issue by echoopen** [Chainlit/cookbook#12]
I'm very sorry, but I'm having this problem with the pinecone example: "Document prompt requires documents to have metadata variables: ['source']. Received document with missing metadata: ['source']."

**Comment by willydouhard** [comment]
Don't be sorry! It looks like the documents you embedded and persisted in your pinecone miss an attribute. If you use the pdf-qa example does it work? (it is the same as the pinecone example but it also creates the vectors from the uploaded pdf)

**Comment by echoopen** [comment]
The pdf example works, but the pdf example has this code:
docs = text_splitter.split_documents (documents)
        for i, doc in enumerate(docs).
            doc.metadata["source"] = f "source_{i}"
        return docs

But I use DirectoryLoader to load the txt text into docs, after using the above code, still report this error, if it is convenient, convenient to give me a simple DirectoryLoader will be stored in the vector Pinecone example?
Mine is docsearch = Pinecone.from_texts(split_docs, embeddings, index_name=index_name)

**Comment by willydouhard** [comment]
I found [this example](https://gist.github.com/Jason-CKY/f67bcc07d6beb72bc924a10694907430) showing how to use`DirectoryLoader` with sources.
