### ISSUE TITLE
Add CDK deployment option for AWS ECS in the cookbook (Implemented)

### ISSUE THREAD

**Issue by SokiKawashima** [Chainlit/cookbook#133]
The AWS ECS deployment guide in the cookbook now includes a CDK (Cloud Development Kit) option for automated deployment. This has been implemented in a new directory `aws-ecs-cdk-deployment`.

Implementation details:
1. Created a new directory `aws-ecs-cdk-deployment` with CDK stack definition
2. Implemented CDK stack using TypeScript, including:
   - VPC creation
   - ECS cluster setup
   - Docker image building and pushing to ECR
   - Fargate service with Application Load Balancer
3. Reused existing `app.py` and `Dockerfile` from the manual deployment guide
4. Updated README.md to include instructions for CDK deployment

Key features of the CDK implementation:
- Uses `aws-cdk-lib` for infrastructure definition
- Creates a VPC with 2 Availability Zones
- Sets up an ECS cluster
- Builds and pushes Docker image to ECR
- Creates a Fargate service with Application Load Balancer
- Outputs the URI of the Docker image

Benefits:
- Simplified deployment process (single `cdk deploy` command)
- Infrastructure-as-Code approach for better version control and reproducibility
- Easier customization and extension of the deployment setup
- Support for both x86 and ARM-based development environments

Next steps:
1. Review and merge the implemented changes
2. Update the main cookbook README to reference this new deployment option
3. Consider adding more advanced features like custom domain setup, SSL certificates, etc.

Feedback and suggestions for improvements are welcome!

**Comment by ModEnter** [comment]
Hello, this issue has beeen merged, thanks a lot for your kind contribution to make the chainlit cookbook better !
