### ISSUE TITLE
Update Haystack example to version 2.0?

### ISSUE THREAD

**Issue by smach** [Chainlit/cookbook#139]
The Haystack example uses  Haystack version 1.0 and says on the web  “The current Haystack integration allows you to run chainlit apps and visualise intermediary steps. Playground capabilities will be added with the release of Haystack 2.0.”
https://docs.chainlit.io/api-reference/integrations/haystack#haystack

Haystack version 2.9 was released in March 2024 and I’d rather use that going forward. Is it possible to update your Haystack example to Haystack 2.0? Thanks.

**Comment by constantinidan** [comment]
Thank you for your comment. We welcome contributions on https://github.com/Chainlit/chainlit/issues/869
