### ISSUE TITLE
Add llama.ccp example

### ISSUE THREAD

**Issue by constantinidan** [Chainlit/cookbook#14]
Create an example using https://github.com/ggerganov/llama.cpp

**Comment by willydouhard** [comment]
This issue is a pretty good example. Might be worth it to turn it into a cookbook example https://github.com/Chainlit/chainlit/issues/345

**Comment by sqrt676** [comment]
can't we use HuggingFace LLAMA API?

**Comment by willydouhard** [comment]
Just added an [example](https://github.com/Chainlit/cookbook/blob/main/huggingface-hub/app.py) with hugging face hub

**Comment by DenisSergeevitch** [comment]
@willydouhard your example is 404 now
