### ISSUE TITLE
 @chainlit/react-client package is trying to import swr with a default import, but swr doesn't have a default export

### ISSUE THREAD

**Issue by S0mt0** [Chainlit/cookbook#140]
I keep getting the following error:
```
Failed to compile

Next.js (14.2.5) out of date (learn more)
./node_modules/@chainlit/react-client/dist/index.mjs
Attempted import error: 'swr' does not contain a default export (imported as 'Zt').
```
Please what is the fix for this?

**Comment by ModEnter** [comment]
Hello, adding 'use client' at the top of the page should do the trick 😉 Don't forget to update Next.js to avoid the out-of-date warning

**Comment by S0mt0** [comment]
> Hello, adding 'use client' at the top of the page should do the trick 😉 Don't forget to update Next.js to avoid the out-of-date warning

Thank you
