### ISSUE TITLE
Chainlit and OpenAI's structured output

### ISSUE THREAD

**Issue by stratosMoschidis** [Chainlit/cookbook#141]
Hi !

I’d like to propose the creation of an example that showcases how to use Chainlit in conjunction with OpenAI's structured output. OpenAI's structured output aim is to enhance data extraction from user interactions and large language models (LLMs), improving efficiency in multi-agent applications.

If you’re interested in moving forward with this proposal or need more details, please let me know
Regards,
Stratos

**Comment by constantinidan** [comment]
Thank you for your proposal. We have examples using OpenAI Tool Calling, which is still preferred for Agents. We have other specific work - send me an email at dan@literalai.com
Thanks!
