### ISSUE TITLE
Need an example for querying from an existing vector DB with the RetrievalQAWithSourcesChain

### ISSUE THREAD

**Issue by PrashantSaikia** [Chainlit/cookbook#36]
We have [this example](https://github.com/Chainlit/cookbook/blob/main/chroma-qa-chat/app.py) for querying on a single document by constructing a vector DB on the fly. I have multiple PDFs on which I want to query, and I have already created a Weaviate vectorstore ([here](https://gist.github.com/PrashantSaikia/d6a5be8a0e7e236207e759366e2becc5)). So, how do I modify [this](https://github.com/Chainlit/cookbook/blob/main/chroma-qa-chat/app.py) to be able to query on my existing vector DB?

[Here](https://gist.github.com/PrashantSaikia/41c4bbd06df2b38c5e54f131ee642fec) is my attempt, I'm getting stuck at extracting the sources. Perhaps the structure of the sources output are different in chroma DB and Weaviate, not sure. Any help is appreciated. This is the error I get:

```
File "C:\Users\username\Documets\app.py", line 122, in main
    index = all_sources.index(source_name)
            ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'index'
```
Here is the output I get:

<img width="748" alt="image" src="https://github.com/Chainlit/cookbook/assets/39755678/4b344f1e-96e3-44d4-b2ed-308cb8b1161e">

**Comment by willydouhard** [comment]
I think you should get the sources as shown [here](https://github.com/Chainlit/cookbook/blob/main/pdf-qa/app.py#L135). This example use `ConversationalChain` but I think it should work the same for `RetrievalChain`.
