### ISSUE TITLE
OpenAI assistant example

### ISSUE THREAD

**Issue by ryanshrott** [Chainlit/cookbook#40]
1. images not working:
'MessageContentImageFile' object has no attribute 'text'

2. Show all steps please with code interpreter 

3. Enable streaming.

**Comment by willydouhard** [comment]
Can you explain the procedure to reproduce the error with `MessageContentImageFile` ?

**Comment by ryanshrott** [comment]
make a plot of f(x)=x^3

**Comment by ryanshrott** [comment]
also, some of the markdown for equations is not being displayed properly

**Comment by willydouhard** [comment]
Thanks! Will take a look

**Comment by willydouhard** [comment]
I have updated the cookbook example (including the assistant instructions).

<img width="991" alt="Screenshot 2023-11-09 at 13 41 08" src="https://github.com/Chainlit/cookbook/assets/13104895/efa41989-bc83-499b-a9cd-222eeb93aec4">
<img width="1051" alt="Screenshot 2023-11-09 at 13 40 11" src="https://github.com/Chainlit/cookbook/assets/13104895/407cc8b1-5d11-47d6-98a1-9ce4a478514e">

These results are only achievable with this [version of Chainlit ](https://github.com/Chainlit/chainlit/pull/530). Will try to make a RC release today.

**Comment by willydouhard** [comment]
Just updated the cookbook example to display messages as they go. Check the [video](https://github.com/Chainlit/cookbook/tree/main/openai-assistant).

**Comment by ryanshrott** [comment]
thanks is it on pypi yet?

**Comment by willydouhard** [comment]
yes, run `pip install --pre chainlit`

**Comment by ryanshrott** [comment]
Latest version. How to enable it?

**Comment by ryanshrott** [comment]
@willydouhard im on latest. How to enable it?

**Comment by willydouhard** [comment]
In your config.toml file under [feature ](https://docs.chainlit.io/backend/config/features)
