### ISSUE TITLE
OpenAI Assistant Example

### ISSUE THREAD

**Issue by ozanyurt** [Chainlit/cookbook#49]
![image](https://github.com/Chainlit/cookbook/assets/327332/de6008d6-c3c7-4be4-a9a9-24e4867ecc43)

Hello, 

I am starting the app.py file as shown in the given example. Everything is working, but the final generated image is not being displayed. I have shared the screenshot of the result.

**Comment by willydouhard** [comment]
Seems like you are not using the latest version of chainlit. Can you run `pip install -U chainlit`?

**Comment by ozanyurt** [comment]
Seems like you were right about the version issue. I couldn't install the latest version in a strange way because I'm using Python version 3.12. But when I set up a new environment, I realized the problem.

Version 0.7.501 is working with Python 3.12.

I'm running it smoothly now. Thank you for your help and for this wonderful project.

**Comment by ozanyurt** [comment]
Thanks I am closing this.
