### ISSUE TITLE
/image-gen doesn't work with Python 3.11

### ISSUE THREAD

**Issue by tymrtn** [Chainlit/cookbook#50]
When running the image-gen demo on python 3.11 it throws an error:
ModuleNotFoundError: No module named 'stability_sdk'

Workaround is to run everything on python3.10.

**Comment by willydouhard** [comment]
I think it is because you have `stability_sdk` installed with your python 11 pip but not with your python 3.10 pip.

**Comment by ModEnter** [comment]
This isssue has been resolved, I'm closing it. Feel free to ask technical questions on the Chainlit Discord server to interact directly with the Chainlit community ⚡
