### ISSUE TITLE
Is it possible to upload video files?

### ISSUE THREAD

**Issue by daniellefranca96** [Chainlit/cookbook#54]
I would like to upload videos files so the chat can make tanscriptions and summaries of them. Is it possible?

**Comment by willydouhard** [comment]
It should be possible through https://docs.chainlit.io/chat-experience/multi-modal and https://docs.chainlit.io/api-reference/ask/ask-for-file

**Comment by ModEnter** [comment]
This isssue has been answered, I'm marking it as resolved
