### ISSUE TITLE
How to get the "source_documents" with chainlit 0.7??

### ISSUE THREAD

**Issue by wangpengfei2048** [Chainlit/cookbook#57]
I get the source_documents with chainlit 0.6:
code :
@cl.on_message
async def main(message: cl.Message):
    chain = cl.user_session.get("chain")  # type: ConversationalRetrievalChain
    cb = cl.AsyncLangchainCallbackHandler()

    res = await chain.acall(message.content, callbacks=[cb])
    answer = res["answer"]
    source_documents = res["source_documents"]  # type: List[Document]
    ....

      I use chainlit 0.7 now , I use this code to get the answer:
code:
    async for chunk in runnable.astream(
        message.content,
        config=RunnableConfig(callbacks=[cl.LangchainCallbackHandler()]),
    ):
        await res.stream_token(chunk)

     the result "res" is “Message”, how to get the “source_documents”？

**Comment by willydouhard** [comment]
This is a Langchain question but I am not sure you can get the source documents with the `astream` method

**Comment by wangpengfei2048** [comment]
Yes , It is a Langchain question, there are two different methods to ask.  chainlit also changes it  using LCEL.
and I change it , but I want to use source_documents as before,  can you give some suggestion?? there is an example with chainlit ,but the old method.. 

https://docs.chainlit.io/examples/qa

**Comment by willydouhard** [comment]
[This post ](https://discord.com/channels/1088038867602526210/1189649934824263833/1189922832780644484 )on discord covers that I believe.

**Comment by wangpengfei2048** [comment]
what is the link,  i cant reach it. 

now  I use astream_log() to get the  answer and the source_documents

**Comment by ModEnter** [comment]
Glad you found a way to solve your issue ! I'm marking is as resolved 😉
