### ISSUE TITLE
Unable to parse output in `langchain-ask-human` example

### ISSUE THREAD

**Issue by gameveloster** [Chainlit/cookbook#58]
Tried running the `langchain-ask-human` example provided at https://github.com/Chainlit/cookbook/blob/b0e0a0c6f78c5ab69c10d32d6763bea9871ee69e/langchain-ask-human/app.py

However, when I ask the question `I need to order pizza for a hackathon. How many should I order?` just like in the video `ask-human.mp4`, I get the error

```
An output parsing error occurred. In order to pass this error back to the agent and have it try again, pass handle_parsing_errors=True to the AgentExecutor. This is the error: Could not parse LLM output: Thought: I should ask a human for guidance.
Action:
{
"action": "human",
"action_input": "How many people are attending the hackathon?"
}
```

Anyone knows the solution to this? Thanks

---

My packages:
```
chainlit                                 0.7.700
langchain                                0.0.352
langchain-community                      0.0.6
langchain-core                           0.1.3
openai                                   0.27.4
```

**Comment by willydouhard** [comment]
what model are you using? It looks like the model is not able to produce a correct output format.

**Comment by gameveloster** [comment]
@willydouhard `gpt-3.5-turbo`.

Any suggestions on which 7B open weights model is suitable for this task?

**Comment by willydouhard** [comment]
You can try mistral instruct. You can also try gpt 4 quickly just to check if it fixes the bug
