### ISSUE TITLE
How to create a link, or more information, to the source retrieved by OpenAI Assistant?

### ISSUE THREAD

**Issue by wodecki** [Chainlit/cookbook#62]
I run the OpenAI assistant as a retrieval over my documents.
When I ask the question, it answers correctly, but the source provided is a non-clickable [{some_number}+source], see picture below:
<img width="746" alt="image" src="https://github.com/Chainlit/cookbook/assets/14348685/9e5f85b1-cc95-4bfa-8de0-089eb6cde44f">
How to make a bot to provide more precise information on the source (preferably document name/paragraph)?

**Comment by willydouhard** [comment]
I don't know if OpenAI assistant can provide a link to the source of the content of the source. You might want to check the tools invoked but your run. Maybe the retriever does provide the used source. Then you can use markdown ou the Text element to add a clickable link.

**Comment by zjffdu** [comment]
Similar question, does chainlit support to display link in response?

**Comment by ModEnter** [comment]
You can find information about the source retrieval [here](https://platform.openai.com/docs/assistants/deep-dive/managing-threads-and-messages), although it seems that there are [many issues](https://community.openai.com/t/assistant-citations-annotations-array-is-always-empty/476752) reported by the OpenAI community. Chainlit does not natively implements a way to display the source, but you can retrieve them and display them "manually" in you message.
