### ISSUE TITLE
How can I access user feedback in the main python script?

### ISSUE THREAD

**Issue by benoitmiserez** [Chainlit/cookbook#66]
I'm just getting to know it but I already think Chainlit is awesome! 

However, I would like to access the user feedback in the main python script for further analysis. I cannot find it in the documentation or issues. Data persistence is enabled and I can find the feedback in the Literal AI dashboard. 

How can I access the feedback in the main python script?

Thanks!

**Comment by willydouhard** [comment]
Thank you!

1. You can access your data with the [literal sdk ](https://docs.getliteral.ai/python-client/api-reference/thread)
2. You can override the [chainlit data layer](https://github.com/Chainlit/chainlit/blob/main/backend/chainlit/data/__init__.py#L222)

**Comment by benoitmiserez** [comment]
Thanks! 
Do you have an example of how to do this elegantly? I'm working on a langchain RAG application. Do I create a separate step for it? I'm not familiar with threads either.

**Comment by willydouhard** [comment]
What are you looking to achieve with the feedback exactly?

**Comment by benoitmiserez** [comment]
I want to use it to create canned answers. If the feedback is good, I want to store the question answer pair in my vector db.

I can add code to chainlit/data/__init__.py in order to create a custom data layer or to modify ChainlitDataLayer, but I suppose there's better ways to do this?

**Comment by benoitmiserez** [comment]
Worked around the issue. My current solution is:
- updated app.main() (@cl.on_message) to write question and answer to the local database with id attribute
- updated chainlit.server.update_feedback() to find the answer in the database with answer.id==update.feedback.forId (as mentioned [here](https://github.com/Chainlit/chainlit/issues/95)) and write update.feedback.value and update.feedback.comment to this record
Thanks!

**Comment by willydouhard** [comment]
Awesome!
