### ISSUE TITLE
Request to Add Google Gemini Pro and Gemini Pro Vision Examples

### ISSUE THREAD

**Issue by sathyanaravind** [Chainlit/cookbook#71]
I would like to kindly request the inclusion of examples for the Google Gemi Pro and Gemini Pro Vision in the Chainlit Cookbook repository.
Specifically I would like to add
- text generation and chatbot example with gemini-pro
- mutimodal image and text question answering with gemini-vision-pro
Both of these projects are noteworthy in their respective domains and can greatly benefit the community by showcasing their capabilities and integration potential within the Chainlit framework.

**Comment by constantinidan** [comment]
Contributions are welcomed! Thanks
