### ISSUE TITLE
Working with open source models

### ISSUE THREAD

**Issue by zbabarMRMR** [Chainlit/cookbook#72]
Is it possible to work with Open source models like LLama2 using Ollama? I have tried but somehow it did not work and constantly asks for OpenAI key.

**Comment by zbabarMRMR** [comment]
Yes I had almost a similar configurations but still chainlit says you to configure OpenAI key

**Comment by willydouhard** [comment]
Chainlit does not require an openai key, can you provide the exact error trace?
