### ISSUE TITLE
Question: Can this example be easily adapted for MS SQL Server or PostgreSQL

### ISSUE THREAD

**Issue by scheung38** [Chainlit/cookbook#75]
https://github.com/Chainlit/cookbook/blob/main/bigquery/app.py

**Comment by ModEnter** [comment]
Yes, you can implement any additional backend logic on your side, in the `app.py` file. You could for example use sql databases to store the queries and the answers by adding logic for SQLAlchemy (or equivalent framework) in the cl.on_message
