### ISSUE TITLE
When the openAI assistant is running, there is nothing in the UI to let the user know it's working

### ISSUE THREAD

**Issue by dividor** [Chainlit/cookbook#85]
I am testing the cool OpenAI assistant example:

https://github.com/Chainlit/cookbook/tree/main/openai-assistant

One thing I've noticed is that on multi-step tasks where the assistant first responds with text, then goes on to do more steps, there is nothing in the chainlit UI to indicate the assistant is working. No spinning wheels, no "Running", even though in fact the assistant is working and will output something. This has confused users. I have looked through the documentation for something to display, but can't seem to find anything. 

Is there any way to put something in the UI to indicate the assistant is working?

**Comment by ModEnter** [comment]
Hello, this is a known issue addressed [here](https://github.com/Chainlit/chainlit/issues/1254). We're working on it, I'm closing this issue to avoid duplicate issues
