### ISSUE TITLE
Fix for custom front end , playground.tsx 

### ISSUE THREAD

**Issue by btebbutt** [Chainlit/cookbook#88]
In the backend example provided in the cookbook is used, the chat UI works well , however as soon as other libraries that use their own call backs are inserted into the backend , every time the LLM responds , there is a blank empty text box created . E.g. 

<img width="544" alt="image-bug" src="https://github.com/Chainlit/cookbook/assets/55270549/3970ef16-0bdb-49cd-adb7-ab2c0ac70aea">

this is fixed by adding a small condition in the render message function within playground.tsx : 

![image](https://github.com/Chainlit/cookbook/assets/55270549/7658878f-8d88-4b7b-984a-f2973982b266)

**Comment by ModEnter** [comment]
Hello, since the playground has been removed from chainlit, I'm closing this issue. Feel free to ask any code-related question on the Chainlit's discord, to interact directly with the chainlit community 😉
