### ISSUE TITLE
Custom react frontend with chainlit backend , chainlit stop sending message to frontend if some tasks takes ~> 42 sec

### ISSUE THREAD

**Issue by suman12345678** [Chainlit/cookbook#89]
Hi Team,

I am using react as frontend and chainlit server as backend. I have a call from chainlit backend which sometimes takes ~> 42 sec. For those responses I dont see the messages coming to react frontend. When the response time is less I get it always.

Could you please let me know how can I solve this? are there any setting I can change?

**Comment by Kota-11711406** [comment]
Same getting issue with sending message to front end by chainlit backend.

**Comment by ModEnter** [comment]
The issue likely comes from your modifications, since there is no timeout for the base react frontend (I reproduced the experiment with a 300s wait time, and the frontend got the answer right).
