### ISSUE TITLE
azure-openai-pinecone-pdf-qa - Found document with no 'text' key. Skipping

### ISSUE THREAD

**Issue by croziermaxime** [Chainlit/cookbook#93]
Hey, I'm currently running the azure-openai-pinecone-pdf-qa locally on my machine, i've set up all the things correctly, the indexation of the pdfs are working as expected: 
![image](https://github.com/Chainlit/cookbook/assets/72015566/3ed25a2d-9fe0-4da1-bb92-252593147fba)
but once the app is running and i'm trying to make request about the document i get this message: 
![image](https://github.com/Chainlit/cookbook/assets/72015566/84ca11f2-7bdd-4f5a-902d-bde298ca887f)
so the RAG isn't working and the response it gives me is not according to the document.
I've tried with multiple pdf's stored in my ./pdfs directory even the one from the repository but nothing changes it's always the same.

If anyone could help me I'll be really grateful, Thanks !

**Comment by Kotrotsos** [comment]
I have this exact same issue with just the OpenAI LLM. It just fetches its knowledge from the LLM instead of the loaded data. Pinecone has the vectors loaded, I can query it using pinecone-client just fine.

**Comment by ModEnter** [comment]
The way of initializing the pinecone client has been updated. Thanks for your feedback
