### ISSUE TITLE
Use cl.Action on custom frontend

### ISSUE THREAD

**Issue by croziermaxime** [Chainlit/cookbook#96]
Hey I'm trying to use the chainlit actions inside the custom frontend like this: 
![image](https://github.com/Chainlit/cookbook/assets/72015566/661eb42d-654d-49b0-b423-dd2c9cbd08b6)
But the 2 actions are not displaying in the frontend when I run it, I guess I have to apply changes directly to the frontend to make it work, but I wonder if the cl.Action method is supported on the @chainlit/react-client module and if so what should I do to make it work.

Thanks !

**Comment by ModEnter** [comment]
Hello, to display [actions](https://docs.chainlit.io/concepts/action#action) in a message, you can pass them directly as attribute to the message, as shown in this comprehensive example :

```python
import chainlit as cl

@cl.on_chat_start
async def start():
    # Sending an action button within a chatbot message
    actions = [
        cl.Action(name="action_button", value="example_value", description="Click me!")
    ]

    await cl.Message(content="Interact with this action button:", actions=actions).send()
    ```
